name: house-price-prediction
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - contourpy=1.3.1
  - cycler=0.11.0
  - expat=2.6.4
  - fonttools=4.55.3
  - freetype=2.12.1
  - icu=73.1
  - intel-openmp=2024.2.1
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.9.0
  - libmpdec=4.0.0
  - libpng=1.6.39
  - libpq=17.4
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2024.2.2
  - numpy=2.2.3
  - openjpeg=2.5.2
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.0
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.13
  - pytz=2024.1
  - qtbase=6.7.2
  - qtdeclarative=6.7.2
  - qtsvg=6.7.2
  - qttools=6.7.2
  - qtwebchannel=6.7.2
  - qtwebsockets=6.7.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - setuptools=75.8.0
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.45.3
  - tbb=2021.13.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
